trigger:
  batch: true
  branches:
    include:
      - master
      - 'refs/tags/v*'
  paths:
    exclude:
      - 'README.md'
      - 'CCF-TECHNICAL-REPORT.pdf'
      - 'Doxyfile'
      - 'THIRD_PARTY_NOTICES.txt'
      - 'getting_started/'
      - 'sphinx/'
      - '.github/'
      - '.azure-pipelines-gh-pages.yml'
      - 'LICENSE'

pr:
  autoCancel: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

schedules:
- cron: "0 3 * * Mon-Fri"
  displayName: Daily morning build
  branches:
    include:
    - master
  always: true

resources:
  containers:
    - container: nosgx
      image: ccfciteam/ccf-ci-18.04-oe-8fe3697:latest
      options: --publish-all --cap-add SYS_PTRACE -v /dev/shm:/tmp/ccache -v /mnt/build:/__w/

    - container: sgx
      image: ccfciteam/ccf-ci-18.04-oe-8fe3697:latest
      options: --publish-all --device /dev/sgx:/dev/sgx -v /dev/shm:/tmp/ccache -v /mnt/build:/__w/

variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
    perf_or_release: release
  ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v')) }}:
    perf_or_release: perf

jobs:
- template: .azure-pipelines-templates/matrix.yml
  parameters:
    perf_or_release: ${{ variables['perf_or_release'] }}
