pr:
  branches:
    include:
      - master
  paths:
    include:
      - .daily.yml
      - .azure-pipelines-templates/*

trigger: none

schedules:
- cron: "0 3 * * Mon-Fri"
  displayName: Daily build
  branches:
    include:
    - master
  always: true

resources:
  containers:
    - container: nosgx
      image: ccfciteam/ccf-ci-18.04-oe-8fe3697:latest
      options: --publish-all --cap-add SYS_PTRACE -v /dev/shm:/tmp/ccache -v /mnt/build:/__w/

    - container: sgx
      image: ccfciteam/ccf-ci-18.04-oe-8fe3697:latest
      options: --publish-all --device /dev/sgx:/dev/sgx -v /dev/shm:/tmp/ccache -v /mnt/build:/__w/

jobs:
- template: .azure-pipelines-templates/daily-matrix.yml
