parameters:
  env:
    NoSGX:
      container: nosgx
      pool: Ubuntu-1804-D16s_v3
    SGX:
      container: sgx
      pool: Ubuntu-1804-DC8_v2

  build:
    NoSGX:
      cmake_args: '-DCOMPILE_TARGETS=virtual'
    SGX:
      cmake_args: '-DCOMPILE_TARGETS=sgx'
    debug:
      cmake_args: '-DCMAKE_BUILD_TYPE=Debug -DSAN=ON -DCOVERAGE=ON -DBUILD_SMALLBANK=OFF'
    install:
      install_prefix: '/tmp/ccf-install'
      cmake_args: '-DCMAKE_INSTALL_PREFIX=/tmp/ccf-install'

jobs:
  - template: common.yml
    parameters:
      target: NoSGX
      env: '${{ parameters.env.NoSGX }}'
      cmake_args: '${{ parameters.build.debug.cmake_args }} ${{ parameters.build.NoSGX.cmake_args }}'
      suffix: 'Coverage'
      artifact_name: 'NoSGX_Coverage'
      ctest_filter: '-LE "perf|suite"'

  - template: common.yml
    parameters:
      target: SGX
      env: '${{ parameters.env.SGX }}'
      cmake_args: '${{ parameters.build.install.cmake_args }} ${{ parameters.build.SGX.cmake_args }} -DTLS_TEST=ON -DSHUFFLE_SUITE=ON'
      suffix: 'Release'
      artifact_name: 'SGX_Release'
      ctest_filter: '-LE "benchmark|perf"'
      install_prefix: '${{ parameters.build.install.install_prefix }}'