steps:
- script: |
    ninja install
  workingDirectory: build
  displayName: 'Install'

- script: |
    mkdir -p nested/run
    cd nested/run
    python3.7 -m venv env
    source env/bin/activate
    python -m pip install -U -r ${{ parameters.install_prefix }}/bin/requirements.txt
    pip freeze > ${{ parameters.install_prefix }}/bin/requirements.txt
    timeout --signal=SIGINT --kill-after=60s --preserve-status 60s \
      python ${{ parameters.install_prefix }}/bin/start_network.py \
      -p ../../build/liblogging \
      -b ${{ parameters.install_prefix }}/bin \
      -g ../../src/runtime_config/gov.lua \
      -v
  displayName: Test installed CCF

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: ${{ parameters.install_prefix }}
    archiveType: 'tar'
    tarCompression: 'gz'
    archiveFile: '$(Build.ArtifactStagingDirectory)/ccf.tar.gz'
    verbose: true
  displayName: 'Create Install Tarball'

- task: PublishPipelineArtifact@1
  inputs:
    path: $(Build.ArtifactStagingDirectory)/ccf.tar.gz
    artifact: ccf.tar.gz
    displayName: 'Publish CCF Install'