parameters:	
  artifact_name: ''

steps:
- script: |
    tar -cavf artifact.tar.gz `find . -maxdepth 1 -type f | grep -v CMakeCache.txt`
  displayName: Compress build artifact
  workingDirectory: build

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: ${{ parameters.artifact_name }}
    targetPath: build/artifact.tar.gz

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: '${{ parameters.artifact_name }} TLS report'
    targetPath: build/tls_report.html